site_name: MkDocs Mermaid to Image Plugin
site_url: https://nuitsjp.github.io/mkdocs-mermaid-to-svg/
repo_url: https://github.com/nuitsjp/mkdocs-mermaid-to-svg

theme:
  name: material
  language: en

extra_css:
  - stylesheets/pdf-fixes.css

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.highlight
  - toc:
      permalink: true

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: ja
          name: 日本語
          build: true
  - mermaid-to-svg:
      # PDF生成時の互換性のためHTMLラベルを無効化
      mermaid_config:
        htmlLabels: false
        flowchart:
          htmlLabels: false
        class:
          htmlLabels: false
  - to-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      cover_subtitle: 'MkDocs Mermaid to Image'
      toc_title: 目次
      toc_level: 3
      output_path: mkdocs-mermaid-to-svg.pdf

nav:
  - Home: index.md
  - Architecture: architecture/index.md

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: 日本語
      link: /ja/
      lang: ja
